image: node:18

pipelines:
  branches:
    main:
      - step:
          name: "Deploy do Frontend"
          caches:
            - node
          script:
            - echo "üì¶ Instalando depend√™ncias"
            - npm install
            - echo "üèóÔ∏è Gerando build"
            - npm run build
            - echo "üßπ Limpando pasta dist no servidor"
            - |
              apt-get update && apt-get install -y openssh-client
              ssh -o StrictHostKeyChecking=no -p $DEPLOY_SSH_PORT $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST "rm -rf $DEPLOY_FRONTEND_PATH/*"
            - echo "üöÄ Enviando arquivos para o servidor via SCP"
            - |
              scp -P $DEPLOY_SSH_PORT -r dist/* $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST:$DEPLOY_FRONTEND_PATH/
            - echo "üîÑ Ajustando permiss√µes e reiniciando container Docker"
            - |
              ssh -o StrictHostKeyChecking=no -p $DEPLOY_SSH_PORT $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST "chmod -R 755 $DEPLOY_FRONTEND_PATH/ && docker restart $DEPLOY_CONTAINER_NAME"
